### ISSUE TITLE
Item Name

### ISSUE THREAD

**Issue by skeenp-dcceew** [skeenp/agol_backup#7]
Remove reference to i['name'] when determining if exportable

**Comment by skeenp** [comment]
Need to get check where this is an error, and how it was modified on skeenp-lls

**Comment by skeenp-dcceew** [comment]
title = f"{item['name']}{postfix}" > title = f"{item['title']}{postfix}" in backup_item.py

if i['type'] == "Feature Service" and i['name']: > if i['type'] == "Feature Service": in backup_cfg_mgr.py
